application: white-terra-413
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: roadtrip.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.1"